use_frameworks!

target 'Segment-ComScore_Example' do
  pod 'Segment-ComScore', :path => '../'

  target 'Segment-ComScore_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  end
end
