
target 'Segment-ComScore_Example' do
  pod 'Segment-ComScore', :path => '../'
end


target 'Segment-ComScore_Tests' do
  pod 'Segment-ComScore', :path => '../'
  pod 'OCMockito'
  pod 'Specta'
  pod 'Expecta'
end
