platform :ios, '11.0'

target 'Segment-ComScore_Example' do
  pod 'Segment-ComScore', :path => '../'
end


target 'Segment-ComScore_Tests' do
  inherit! :search_paths
  use_frameworks!
  pod 'Segment-ComScore', :path => '../'
  pod 'OCMockito'
  pod 'Specta'
  pod 'Expecta'
end
